/******************** Création des tables de la base de donnée **************/
/*
CREATE TABLE UTILISATEUR(
   ID INT AUTO_INCREMENT,
   LOGIN VARCHAR(50),
   MODE_DE_PASSE VARCHAR(255),
   PRIMARY KEY(ID)
);
*/


USE erp;
CREATE TABLE TVA(
   ID INT AUTO_INCREMENT,
   LIBELLE VARCHAR(50),
   TAUX DECIMAL(4,2),
   PRIMARY KEY(ID)
);

CREATE TABLE CLIENT(
   ID INT AUTO_INCREMENT,
   CIVILITE VARCHAR(20),
   NOM VARCHAR(50),
   PRENOM VARCHAR(50),
   ADRESSE1 VARCHAR(250),
   ADRESSE2 VARCHAR(250),
   CODE_POSTAL VARCHAR(6),
   VILLE VARCHAR(80),
   TEL VARCHAR(16),
   EMAIL VARCHAR(50),
   ID_TVA INT,   
   PRIMARY KEY(ID),
   FOREIGN KEY(ID_TVA) REFERENCES TVA(ID)
);

CREATE TABLE PARAMETRES(
   ID INT AUTO_INCREMENT,
   PARAMETRE VARCHAR(40),
   VALEUR VARCHAR(80),
   PRIMARY KEY(ID)
);

CREATE TABLE ARTICLE(
   ID INT AUTO_INCREMENT,
   DESIGNATION VARCHAR(150),
   PRIX_UNITAIRE DECIMAL(10,5),
   PRIMARY KEY(ID)
);

CREATE TABLE FACTURE (
   ID INT AUTO_INCREMENT,
   NUMERO VARCHAR(16),
   ETAT VARCHAR(150),   
   DATE_FACTURE DATE,
   REMISE DECIMAL(15,2),
   ID_CLIENT INT,
   ID_TVA INT,
   PRIMARY KEY(ID),
   FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID),
   FOREIGN KEY(ID_TVA) REFERENCES TVA(ID)
);

CREATE TABLE LIGNE_FACTURE(
   ID INT AUTO_INCREMENT,
   LIGNE INT,
   DESIGNATION VARCHAR(150),
   PRIX_UNITAIRE DECIMAL(10,5),
   QUANTITE DECIMAL(10,5),
   MONTANT DECIMAL(15,2), 
   ID_ARTICLE INT,
   ID_FACTURE INT,
   PRIMARY KEY(ID),
   FOREIGN KEY(ID_ARTICLE) REFERENCES ARTICLE(ID),
   FOREIGN KEY(ID_FACTURE) REFERENCES FACTURE(ID)
);
